[package]
name = "rlottery"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.11"
postgres = "0.19"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4", features = ["v4"] }
rand = "0.8"
refinery = { version = "0.8", features = ["postgres"] }
refinery-macros = "0.8"
